# Generated by Django 2.2 on 2019-04-14 01:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20190413_1808'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chat',
            old_name='from_user',
            new_name='user',
        ),
    ]
