# Generated by Django 2.2 on 2019-04-18 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20190418_1100'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='Bio',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='Bio: '),
        ),
        migrations.AddField(
            model_name='profile',
            name='Name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Name: '),
        ),
        migrations.AddField(
            model_name='profile',
            name='birth_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Born on: '),
        ),
    ]
