# Generated by Django 2.2 on 2019-04-18 19:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20190418_1224'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='statusi',
            field=models.CharField(blank=True, choices=[('Single and ready to mingle', 'Single and ready to mingle'), ('Of the market', 'Of the market'), ('Married', 'Married'), ('Engaget', 'Engaget')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='birth_date',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Born on: '),
        ),
    ]
