# Generated by Django 2.2 on 2019-04-19 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20190419_1609'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chat',
            old_name='useri',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='profile',
            name='statusi',
            field=models.CharField(blank=True, choices=[('Married', 'Married'), ('Engaget', 'Engaget'), ('In a relationship', 'In a relationship'), ('Single', 'Single')], max_length=50, null=True),
        ),
    ]
