# Generated by Django 2.2 on 2019-04-20 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20190420_0845'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='public',
        ),
        migrations.AlterField(
            model_name='profile',
            name='statusi',
            field=models.CharField(blank=True, choices=[('Married', 'Married'), ('Engaget', 'Engaget'), ('In a relationship', 'In a relationship'), ('Single', 'Single')], max_length=50, null=True),
        ),
    ]
