# Generated by Django 2.2 on 2019-04-21 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_auto_20190421_0410'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='to_user',
        ),
        migrations.AlterField(
            model_name='profile',
            name='statusi',
            field=models.CharField(blank=True, choices=[('Married', 'Married'), ('In a relationship', 'In a relationship'), ('Engaget', 'Engaget'), ('Single', 'Single')], max_length=50, null=True),
        ),
    ]
