# Generated by Django 2.2 on 2019-07-10 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_auto_20190709_2259'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='public',
            field=models.BooleanField(default=False, verbose_name='Public'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='statusi',
            field=models.CharField(blank=True, choices=[('In a relationship', 'In a relationship'), ('Married', 'Married'), ('Single', 'Single'), ('Engaget', 'Engaget')], max_length=50, null=True),
        ),
    ]
