# Generated by Django 2.2 on 2019-07-10 06:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_auto_20190709_2321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='friends',
            field=models.ManyToManyField(blank=True, related_name='friends', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='profile',
            name='statusi',
            field=models.CharField(blank=True, choices=[('Married', 'Married'), ('In a relationship', 'In a relationship'), ('Single', 'Single'), ('Engaget', 'Engaget')], max_length=50, null=True),
        ),
    ]
