# Generated by Django 2.2 on 2019-07-10 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_auto_20190709_2323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='statusi',
            field=models.CharField(blank=True, choices=[('In a relationship', 'In a relationship'), ('Single', 'Single'), ('Engaget', 'Engaget'), ('Married', 'Married')], max_length=50, null=True),
        ),
    ]
